name: Log SendGrid Packet

on:
  workflow_dispatch:

jobs:
  log_packet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create symbolic packet log
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          HASH=$(echo -n "Sycamore Holdings|Farzaneh Sedarati|812-236-4101|$TIMESTAMP" | sha256sum | cut -d ' ' -f1)
          echo "## Sycamore Holdings Packet – $TIMESTAMP" > packets/$TIMESTAMP.md
          echo "**Entity:** Sycamore Holdings LLC" >> packets/$TIMESTAMP.md
          echo "**Authority:** Farzaneh Sedarati" >> packets/$TIMESTAMP.md
          echo "**Contact:** 812-236-4101" >> packets/$TIMESTAMP.md
          echo "**Hash:** $HASH" >> packets/$TIMESTAMP.md

      - name: Commit and push
        run: |
          git config user.name "FarzanehBot"
          git config user.email "farzanehsedarati6@gmail.com"
          git add packets/
          git commit -m "Logged symbolic packet for Sycamore Holdings"
          git push

